#!/usr/bin/env python

import sys
from optparse           import OptionParser
from csv                import DictReader
from StringIO           import StringIO
from ooopy.OOoPy        import OOoPy
from ooopy.Transformer  import Transformer
import ooopy.Transforms as     Transforms

if __name__ == '__main__' :
    usage  = \
        '''%prog [-d|--delimiter X] [-o|--output-file <filename>]
           <inputfile> <csv-file>'''
    parser = OptionParser (usage = usage)
    parser.add_option \
        ( "-d", "--delimiter"
        , dest    = "delimiter"
        , help    = "Delimiter of cvs-format (Default Tab)"
        , default = '\t'
        )
    parser.add_option \
        ( "-o", "--output-file"
        , dest    = "output_file"
        , help    = "Output file (defaults to stdout)"
        , default = None
        )
    (options, args) = parser.parse_args ()
    if len (args) != 2 :
        parser.error ('Missing arguments')
        sys.exit (1)
    outfile = options.output_file
    if outfile is None :
        outfile = StringIO ()
    d = DictReader (open (args [1]))
    o = OOoPy (infile = args [0], outfile = outfile)
    t = Transformer \
        ( o.mimetype
        , Transforms.get_meta           (o.mimetype)
        , Transforms.Addpagebreak_Style ()
        , Transforms.Mailmerge          (iterator = d)
        , Transforms.renumber_all       (o.mimetype)
        , Transforms.set_meta           (o.mimetype)
        , Transforms.Fix_OOo_Tag        ()
        )
    t.transform (o)
    o.close ()
    if options.output_file is None :
        sys.stdout.write (outfile.getvalue ())
