#!/usr/bin/env python

import sys
from optparse           import OptionParser
from ooopy.OOoPy        import OOoPy
from ooopy.Transformer  import Transformer
import ooopy.Transforms as     Transforms

if __name__ == '__main__' :
    usage  = '%prog [-o|--output-file <filename>] [file, ...]'
    parser = OptionParser (usage = usage)
    parser.add_option \
        ( "-o", "--output-file"
        , dest    = "output_file"
        , help    = "Output file (defaults to stdout)"
        , default = sys.stdout
        )
    (options, args) = parser.parse_args ()
    if len (args) < 1 :
        infiles = [sys.stdin]
    else :
        infiles = args
    o = OOoPy (infile = infiles [0], outfile = options.output_file)
    if len (infiles) > 1 :
        t = Transformer \
            ( o.mimetype
            , Transforms.get_meta     (o.mimetype)
            , Transforms.Concatenate  (* (infiles [1:]))
            , Transforms.renumber_all (o.mimetype)
            , Transforms.set_meta     (o.mimetype)
            , Transforms.Fix_OOo_Tag  ()
            )
        t.transform (o)
    o.close ()
